fix: add extend flag to opionally generate config within extend key o…
nado1001/style-dictionary-tailwindcss-transformer pull request #350
Opened 2024-03-25 00:49 UTC by pivotpointux

Hi @nado1001,

Apologies, but I decided to abort the previous PR and start this new one (hopefully cleaner), where I've aimed to resolve the issues you raised - all except one, which I need some clarification on please:

"However, when I run it in this state, the format of the generated tailwind.config.js is a bit broken.
I would appreciate the following change.
Please use the sd.config.js in the [example](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/blob/main/example/with-css-variables/sd.config.js) and actually run it to check."

If you could please clarify, I will aim to get this resolved.

Thanks!

2024-03-27 18:39 UTC, pivotpointux commented
@nado1001 Just curious if you had an update on this one?

2024-03-31 06:41 UTC, nado1001 requested changes
Thanks for the PR!

2024-03-31 06:41 UTC, nado1001 commented on README.md
> +//README
Please delete the comments here.

2024-03-31 06:41 UTC, nado1001 commented on src/index.ts
> +// index.ts
Please delete the comments here as well.

2024-03-31 06:41 UTC, nado1001 commented on src/types.ts
> +//types.ts
Please delete the comments here as well.

2024-03-31 06:41 UTC, nado1001 commented on src/utils.ts
> +//utils.ts
Please delete the comments here as well.

2024-04-01 19:02 UTC, pivotpointux commented
@nado1001 Thanks for reviewing! Changes actioned.

2024-04-07 10:54 UTC, nado1001 approved these changes
Thanks! We will release it as version 1.4.2 after this

2024-04-07 10:56 UTC, merged