Support Style Dictionary v4 and add preprocessors config
nado1001/style-dictionary-tailwindcss-transformer pull request #369
Opened 2024-09-11 09:20 UTC by mrajaeim

2024-09-14 12:13 UTC, nado1001 requested changes
Thank you for your contribution!
I'm sorry, but is it possible to have the code in the `README.md` also rewritten as follows?

``````js
import StyleDictionary from 'style-dictionary'
import { makeSdTailwindConfig } from 'sd-tailwindcss-transformer'

const StyleDictionaryTailwind = new StyleDictionary(
  makeSdTailwindConfig({ type: 'all' })
)
await StyleDictionaryTailwind.buildAllPlatforms()
```

2024-09-14 12:13 UTC, nado1001 commented on package.json
> +    "style-dictionary": "^4.1.0",
It would be great if you could get it to v4.1.1

2024-09-15 14:31 UTC, mrajaeim commented
Hi @nado1001,

Thanks for reminding me to update the README. I’ve updated it and also added an integration test to ensure the package works with style-dictionary.

2024-09-21 10:14 UTC, nado1001 approved these changes
Thanks for writing the test as well!

2024-09-21 10:16 UTC, nado1001 requested changes
Sorry, there was an error in `src/tests/integration.test.ts`. Could you please fix it?

2024-09-22 07:10 UTC, mrajaeim commented
Hi @nado1001 ,

I'm not sure why we're getting a type error in the test for the following line:
`import StyleDictionary from 'style-dictionary'`
This error occurs when running `yarn typecheck` in CI, but the tests pass successfully when running `yarn test`.
It might be a misconfiguration in the TypeScript settings.
Thanks for your review!

2024-09-22 10:12 UTC, nado1001 commented
Hi, @mrajaeim 
Thanks for the confirmation!
You are right this seems to be caused by the TypeScript configuration.
As it is difficult to solve the problem immediately at the moment, I am sorry, but could you please delete one of the tests you added?
We will add the test you wrote later after we resolve this issue.

2024-09-22 12:17 UTC, mrajaeim commented
Hi @nado1001,
I’ve deleted the integration test.

2024-09-23 09:46 UTC, nado1001 approved these changes
@mrajaeim 
Thank you very much!
I'll release it right after the merge.

2024-09-23 09:47 UTC, merged